# This note.py file is better than the note.txt, colors are easy to see

'''
The get get_response() method: 
Since some of the links in FCC aren't complete I can't use self.BASE_LINK to load the elements base
on their tag name so I decided to still use that url parameter

'''


# TODO: 🔰⬇⬇⬇
# TODO: Use the API endpoint in techcrunch ✅
# TODO: Watch all the modules(pages) to implement new changes made in the BasicActions ✅
# TODO: Implement main.py to print menu like ✅
# TODO: Try to do a table ✅
# TODO: Re-do FCC, links are bad hackernews too and lobSte ✅
# TODO: fix https validation in hacker news some links are http ✅
# TODO: Pagination option for some posts ✅
# TODO: Repository public ✅
# TODO: More dynamic/colored display console
# TODO: Make a the printing function cleaner
# https://rich.readthedocs.io/en/stable/tables.html